
# =================
# === CONSTANTS ===
# =================

DIGITS = '0123456789'
LETTERS_LOWERCASE = 'abcdefghijklmnopqrstuvwxyz'
LETTERS_UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
LETTERS = LETTERS_LOWERCASE + LETTERS_UPPERCASE
LETTERS_DIGITS = LETTERS + DIGITS
